name: Publish Release
on:
  workflow_dispatch:
  push:
  pull_request:
   branches:
    - default

jobs:
  publish-release:
   runs-on: windows-latest
   timeout-minutes: 5
   if: contains(github.event.head_commit.message, '[release]')

   steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Toolchain
      uses: roblox/setup-foreman@v1
      with:
       token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report Tool Versions
      shell: bash
      run: foreman list

    - name: Get Release Details
      shell: bash
      run: |
        echo "PROJECT_VERSION=`grep -Po '(?<=version = \")([^\"]+)' wally.toml`" >> $GITHUB_ENV
        echo "PROJECT_COMMIT_ID=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV

    - name: Build Project
      shell: bash
      run: |
        find ./src -name "*.spec.lua" -type f -delete
        rojo build default.project.json -o release.rbxmx
        rojo build default.project.json -o release.rbxm

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
       name: ${{ env.PROJECT_VERSION }}
       body: ${{ env.PROJECT_COMMIT_ID }}
       tag_name: ${{ env.PROJECT_VERSION }}
       fail_on_unmatched_files: true
       files: |
         release.rbxm
         release.rbxmx
       draft: true
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
